version: '3.8'

services:
  api:
    container_name: wallet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=wallet_db
      - JWT_SECRET=super_secret_key_change_in_production
      - JWT_EXPIRATION=24h
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - wallet-network

  postgres:
    container_name: wallet-postgres
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres_data: